GET http://localhost:3001/api/orders/

###
POST http://localhost:3001/api/orders/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY4NTI3OTU4NH0.y1yU7fFTWkV0q3fLpA6w1lnvMVAWg8Lv7j5-lI77V14

{
    "paymenttype":1,
    "lat": 23,
    "long": 43,
    "products":[
        {"id":"1","q":11},
        {"id":"2","q":12}]
}
###
GET http://localhost:3001/api/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY4NTI3OTU4NH0.y1yU7fFTWkV0q3fLpA6w1lnvMVAWg8Lv7j5-lI77V14

###
GET http://localhost:3001/api/orders/userOrders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY4NTI3OTU4NH0.y1yU7fFTWkV0q3fLpA6w1lnvMVAWg8Lv7j5-lI77V14

