GET https://abudhabigas.onrender.com/api/users/

###
POST https://abudhabigas.onrender.com/api/users/ HTTP/1.1
content-type: application/json

{
    "name": "test",
    "email": "test@gmail.com",
    "mobile": "009714567876",
    "password": "123456"
}

###
POST https://abudhabigas.onrender.com/api/signup/ HTTP/1.1
content-type: application/json

{
    "name": "test1",
    "email": "test1@gmail.com",
    "mobile": "009714567877",
    "password": "123456"
}

###
POST https://abudhabigas.onrender.com/api/login/ HTTP/1.1
content-type: application/json

{
    "email": "test1@gmail.com",
    "password": "123456"
}
###
GET https://abudhabigas.onrender.com/api/settings/

