GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "name": "test",
    "email": "test@gmail.com",
    "mobile": "009711234567",
    "password": "123456"
}

###
GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "note api",
    "important": true

}

###
POST http://localhost:3001/api/users/signup/ HTTP/1.1
content-type: application/json

{
    "name": "test",
    "email": "test@gmail.com",
    "mobile": "009711234567",
    "password": "123456"
}

###
POST http://localhost:3001/api/users/login/ HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}
###
POST http://localhost:3001/api/users/resetPassword/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY4NTI1OTcwOX0.0Ay8fBv8k63YbPq_0xyJx9Dppe8skfMQ09AjoBPcdfE

{
    "oldpassword": "223456",
        "newpassword": "123456"


}
###
POST http://localhost:3001/api/users/verify/ HTTP/1.1
content-type: application/json

{
    "mobile": "009711234567",
        "code": "1111"


}
###
POST http://localhost:3001/api/users/forgetPassword/ HTTP/1.1
content-type: application/json

{
    "data": "test@gmail.com"


}